# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deploy client

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Check Node v # Node v 확인
        run: node -v
      - name: Install Dependencies # 의존 파일 설치
        run: yarn install --frozen-lockfile
      - name: Build # React Build
        run: yarn build
        
      - name: zip create 

        run: zip -qq -r ./build-fe.zip
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SECRET_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload to S3 # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SECRET_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --region ap-northeast-2 ./build-fe.zip s3://together-client/build-fe.zip
      - name: Deploy # Deploy to EC2
        run: aws deploy create-deployment
          --application-name together-client
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name group
          --s3-location bucket=together-client,key=/**build-fe.zip**,bundleType=zip
